import React, { createContext, useContext, useEffect, useState } from 'react'

type Lang = 'fr' | 'ar'

const translations = {
  fr: {
    // Navigation sidebar
    nav_dashboard: 'Tableau de bord',
    nav_predict: 'Prédiction IA',
    nav_analytics: 'Analytics',
    nav_inventory: 'Santé du Stock',
    nav_suppliers: 'Fournisseurs',
    nav_chat: 'Conseiller IA',
    nav_compare: 'Comparer',
    nav_import: 'Import CSV',
    nav_pricing: 'Tarifs',
    nav_profile: 'Profil',
    nav_products: 'Produits',
    nav_sales: 'Ventes',
    nav_scan_qr: 'Scan QR',
    nav_simulate: 'Simulation',
    nav_reception: 'Réception stock',
    nav_qr_print: 'QR en lot',

    // Actions communes
    btn_save: 'Sauvegarder',
    btn_cancel: 'Annuler',
    btn_delete: 'Supprimer',
    btn_edit: 'Modifier',
    btn_add: 'Ajouter',
    btn_create: 'Créer',
    btn_search: 'Rechercher...',
    btn_export: 'Exporter',
    btn_loading: 'Chargement...',
    btn_confirm: 'Confirmer',
    btn_close: 'Fermer',
    btn_back: 'Retour',
    btn_next: 'Suivant',
    btn_refresh: 'Actualiser',

    // Dashboard
    dash_title: 'Tableau de bord',
    dash_products: 'Produits',
    dash_predictions: 'Prédictions',
    dash_high_risk: 'Risque élevé',
    dash_avg_risk: 'Risque moyen',
    dash_total_sales: 'Ventes totales',
    dash_recent_sales: 'Ventes 30j',
    dash_search_placeholder: 'Rechercher par nom ou référence (SKU)...',
    dash_no_products: 'Aucun produit',
    dash_no_products_sub: 'Commencez par créer un produit pour suivre votre stock',
    dash_predict_all: 'Prédire tout',
    dash_new_product: 'Nouveau produit',
    dash_onboarding_title: 'Bienvenue sur StockSense !',
    dash_onboarding_subtitle: 'Suivez ces 3 étapes pour commencer',
    dash_create_product_btn: 'Créer un produit',

    // Predict
    pred_title: 'Prédiction IA',
    pred_select_product: 'Sélectionner un produit',
    pred_horizon: 'Horizon de prédiction',
    pred_days: 'jours',
    pred_run: 'Lancer la prédiction',
    pred_probability: 'Probabilité de rupture',
    pred_result_high: 'Risque élevé',
    pred_result_medium: 'Risque modéré',
    pred_result_low: 'Risque faible',
    pred_trials_left: 'essais gratuits restants',

    // Inventory Health
    inv_title: 'Santé du Stock',
    inv_product: 'Produit',
    inv_stock: 'Stock',
    inv_daily_sales: 'Vélocité 30j',
    inv_reorder: 'Pt. Réappro',
    inv_coverage: 'Couverture',
    inv_status: 'Statut',
    inv_actions: 'Actions',
    inv_history: 'Historique',
    inv_edit: 'Éditer',
    inv_critical: 'Critique',
    inv_warning: 'Réappro.',
    inv_ok: 'OK',
    inv_overstock: 'Surstock',
    inv_trend: 'Tendance',
    inv_no_products: 'Aucun produit trouvé',
    inv_no_products_sub: 'Créez des produits et enregistrez des ventes pour voir les données',

    // Suppliers
    sup_title: 'Fournisseurs',
    sup_add: 'Ajouter un fournisseur',
    sup_name: 'Nom du fournisseur',
    sup_email: 'Email',
    sup_phone: 'Téléphone',
    sup_lead_time: 'Délai de livraison (jours)',
    sup_no_suppliers: 'Aucun fournisseur enregistré',
    sup_no_suppliers_sub: 'Ajoutez vos fournisseurs pour les associer à vos produits',
    sup_new: 'Nouveau fournisseur',
    sup_edit: 'Modifier le fournisseur',
    sup_create_btn: 'Créer le fournisseur',
    sup_save_btn: 'Enregistrer',

    // Profile
    prof_title: 'Mon profil',
    prof_change_pwd: 'Changer le mot de passe',
    prof_current_pwd: 'Mot de passe actuel',
    prof_new_pwd: 'Nouveau mot de passe',
    prof_confirm_pwd: 'Confirmer',
    prof_alert_pref: "Préférences d'alertes",
    prof_alert_threshold: "Seuil d'alerte email",
    prof_pro_active: 'Plan Pro actif',
    prof_upgrade: 'Passer Pro',
    prof_logout: 'Se déconnecter',
    prof_update_pwd: 'Mettre à jour',
    prof_danger_zone: 'Zone dangereuse',
    prof_danger_sub: 'Déconnectez-vous de tous les appareils.',

    // Predict page extras
    pred_params: 'Paramètres',
    pred_back: 'Retour au dashboard',
    pred_gauge: 'Jauge de risque',
    pred_chart: 'Évolution du risque',
    pred_days_rupture: 'Jours avant rupture estimée',
    pred_rupture_date: 'Date de rupture estimée',
    pred_confidence: 'Intervalle de confiance',
    pred_analysis: 'Analyse...',

    // Inventory Health extras
    inv_refresh: 'Actualiser',
    inv_filter_all: 'Tout',
    inv_filter_critical: 'Critique',
    inv_filter_warning: 'Réappro.',
    inv_filter_ok: 'Sain',
    inv_filter_overstock: 'Surstock',
    inv_abc: 'Classification ABC',
    inv_score_velocity: 'Score vélocité',
    inv_history_title: 'Historique du stock',
    inv_no_movements: 'Aucun mouvement enregistré',
    inv_add_stock: 'Ajouter du stock',
    inv_delete: 'Supprimer',

    // Suppliers extras
    sup_refresh: 'Actualiser',
    sup_contact_email: 'Email de contact',
    sup_phone_label: 'Téléphone',
    sup_lead_label: 'Délai de livraison',
    sup_optional: '(optionnel)',
    sup_loading: 'Chargement...',

    // Dashboard titles
    dash_overview: "Vue d'ensemble en temps réel",
    dash_alerts: 'Alertes stock',
    dash_batch_title: 'Analyse rapide — tous les produits',
    dash_batch_sub: 'Prédictions de rupture sur 30 jours',
    dash_catalog: 'Catalogue produits',

    // Predict subtitle
    pred_subtitle: 'Analysez le risque de rupture de stock',

    // QR Scanner
    scan_title: 'Scanner produit',
    scan_subtitle: 'QR Code · EAN-13 · Code 128 · UPC · et plus',
    scan_point: 'Pointez vers un QR code ou code-barres',
    scan_camera_start: 'Démarrer la caméra',
    scan_manual_label: 'SKU, ID produit ou numéro de code-barres',
    scan_analyze: 'Analyser',
    scan_new_scan: 'Scanner un autre produit',
    scan_new_search: 'Nouvelle recherche',
    scan_no_code: 'Entrez un SKU, un ID ou un numéro de code-barres',
    scan_loading: 'Analyse IA en cours...',
    scan_camera_mode: 'Caméra',
    scan_manual_mode: 'Manuel',

    // Common
    status_subscribed: 'Pro actif',
    status_free: 'Plan gratuit',
    confirm_delete_title: 'Confirmer la suppression',
    confirm_delete_msg: 'Cette action est irréversible.',
    toast_saved: 'Sauvegardé avec succès',
    toast_deleted: 'Supprimé avec succès',
    toast_error: 'Une erreur est survenue',
    theme_light: 'Mode clair',
    theme_dark: 'Mode sombre',
    logout: 'Déconnexion',

    // Risk labels shared
    risk_low: 'Faible',
    risk_medium: 'Modéré',
    risk_high: 'Élevé',
    risk_critical: 'Critique',

    // QR Scanner result + errors
    scan_risk_label: 'Risque de rupture (30j)',
    scan_stock_label: 'Stock',
    scan_safety_label: 'Sécu.',
    scan_delay_label: 'Délai',
    scan_detected: 'détecté',
    scan_err_denied: "Permission caméra refusée. Autorisez l'accès dans les paramètres du navigateur.",
    scan_err_no_cam: 'Aucune caméra détectée sur cet appareil.',
    scan_err_generic: "Impossible d'accéder à la caméra. Essayez le mode manuel.",
    scan_not_found: 'Produit introuvable pour ce code',

    // Dashboard panel content
    dash_qa_predict: 'Lancer une prédiction',
    dash_qa_predict_sub: 'Anticiper les ruptures',
    dash_qa_sale: 'Enregistrer une vente',
    dash_qa_sale_sub: "Mettre à jour l'inventaire",
    dash_qa_analytics: 'Voir les analytics',
    dash_qa_analytics_sub: 'Historique & graphiques',
    dash_see_all: 'Voir tout',
    dash_top_risks: 'Top risques',
    dash_badge_high: 'Élevé',
    dash_badge_medium: 'Modéré',
    dash_batch_empty: 'Cliquez sur "Prédire tout" pour analyser',
    dash_step1_title: 'Créer votre premier produit',
    dash_step1_desc: 'Ajoutez un produit à votre catalogue avec son SKU et délai fournisseur.',
    dash_step1_cta: 'Créer un produit',
    dash_step2_title: 'Saisir votre stock initial',
    dash_step2_desc: 'Enregistrez vos premières ventes ou importez votre historique CSV.',
    dash_step2_cta: 'Saisir une vente',
    dash_step3_title: 'Lancer votre première prédiction IA',
    dash_step3_desc: 'Obtenez la probabilité de rupture et la date estimée pour chaque produit.',
    dash_step3_cta: 'Prédire maintenant',
    dash_step_label: 'Étape',
    dash_alert_stock: 'Stock:',
    dash_alert_reorder: 'Réappro:',
    dash_alert_critical: 'Critique',
    dash_alert_warning: 'Réappro.',
    dash_prod_col: 'Produit',
    dash_delay_col: 'Délai',
    dash_safety_col: 'Stock min.',

    // Predict result panel
    pred_stable: 'Stable',
    pred_no_risk: 'Pas de risque immédiat',
    pred_no_result: 'Aucune prédiction',
    pred_hint: "Sélectionnez un produit et lancez l'analyse",
    pred_rupture_label: 'Rupture estimée',
    pred_confidence_label: 'Intervalle confiance',
    pred_ic_label: 'IC 95%',
    pred_evolution: 'Évolution sur',
    pred_critical_zone: 'Zone critique atteinte vers',

    // CreateProduct
    cp_title: 'Nouveau produit',
    cp_subtitle: 'Ajoutez un produit à votre catalogue',
    cp_back: 'Retour au dashboard',
    cp_name: 'Nom du produit',
    cp_sku: 'SKU',
    cp_sku_note: 'référence unique',
    cp_sku_hint: 'Code unique du produit (ex : PROD-001). Ne peut pas être modifié après création.',
    cp_lead_time: 'Délai de livraison',
    cp_lead_unit: 'jours',
    cp_lead_hint: 'Délai moyen en jours entre la commande fournisseur et la réception en stock',
    cp_safety: 'Stock de sécurité',
    cp_safety_unit: 'unités',
    cp_safety_hint: 'Quantité minimale à toujours garder en stock pour les imprévus',
    cp_initial_stock: 'Stock initial',
    cp_initial_hint: 'quantité actuellement disponible',
    cp_supplier: 'Fournisseur',
    cp_no_supplier: '— Aucun fournisseur —',
    cp_supplier_no_data: 'Aucun fournisseur disponible.',
    cp_supplier_create: 'Créer un fournisseur',
    cp_submit: 'Créer le produit',
    cp_success: 'Produit créé avec succès !',
    cp_error: 'Erreur lors de la création',
    cp_scan_sku: 'Scanner',

    // InventoryHealth panel
    inv_velocity_title: 'Vélocité des ventes par produit',
    inv_velocity_sub: 'Ventes journalières moyennes sur 3 fenêtres',
    inv_units: 'unités',
    inv_stable: 'stable',
    inv_tile_critical: 'Critique (stock 0)',
    inv_tile_warning: 'Réappro. urgente',
    inv_tile_ok: 'Stock sain',
    inv_tile_overstock: 'Surstock',

    // AddSale
    sale_title: 'Enregistrer une vente',
    sale_subtitle: "Décrémenter l'inventaire",
    sale_back: 'Retour au dashboard',
    sale_product: 'Produit',
    sale_product_hint: 'Sélectionnez le produit pour lequel vous enregistrez une vente',
    sale_qty: 'Quantité vendue',
    sale_qty_hint: "Nombre d'unités vendues — le stock sera automatiquement mis à jour",
    sale_delay: 'Délai:',
    sale_min_stock: 'Stock min:',
    sale_submit: 'Enregistrer la vente',
    sale_success: 'Vente enregistrée !',
    sale_error: "Erreur lors de l'enregistrement",
    sale_no_products: 'Aucun produit disponible.',
    sale_create_product: 'Créer un produit',
    sale_loading: 'Chargement des produits...',

    // Analytics
    ana_title: 'Analytics',
    ana_subtitle: 'Vue détaillée de vos données',
    ana_export_pdf: 'Exporter PDF',
    ana_export_pred: 'Prédictions CSV',
    ana_export_sales: 'Ventes CSV',
    ana_products: 'Produits',
    ana_predictions: 'Prédictions totales',
    ana_avg_prob: 'Probabilité moyenne',
    ana_high_risk_sub: 'à risque élevé',
    ana_recent_sales_sub: 'ventes ce mois',
    ana_sales_by_product: 'Ventes par produit',
    ana_no_sales: 'Aucune vente enregistrée',
    ana_risk_dist: 'Répartition des risques',
    ana_no_preds: 'Aucune prédiction',
    ana_history_title: 'Historique des prédictions',
    ana_new_prediction: 'Nouvelle prédiction →',
    ana_no_history: 'Aucune prédiction effectuée',
    ana_error: 'Erreur de chargement des analytics',
    ana_export_ok: 'Export téléchargé !',
    ana_export_error: "Erreur lors de l'export",
    ana_date: 'Date',
    ana_horizon: 'Horizon',
    ana_probability: 'Probabilité',
    ana_risk: 'Risque',
    ana_sales_count: 'ventes',
    ana_preds_count: 'prédictions',
    ana_total: 'au total',
    ana_tooltip_pdf: 'Imprimer ou sauvegarder vos analytics en PDF',
    ana_tooltip_csv: 'Télécharger vos données dans Excel ou Google Sheets',

    // Simulate
    sim_title: 'Simulation de Scénarios',
    sim_subtitle: "Anticipez l'impact avant que ça arrive",
    sim_no_products: 'Aucun produit trouvé',
    sim_no_products_msg: "Créez d'abord un produit dans Produits pour lancer une simulation.",
    sim_product_label: 'Produit à simuler',
    sim_product_none: '— Aucun produit —',
    sim_horizon_label: 'Horizon de prédiction',
    sim_demand_label: 'Variation de demande',
    sim_supplier_label: 'Retard fournisseur',
    sim_event_label: 'Événement externe',
    sim_submit: 'Lancer la simulation',
    sim_submitting: 'Simulation en cours...',
    sim_event_none: 'Aucun événement',
    sim_event_ramadan: 'Ramadan',
    sim_event_weather: 'Météo extrême',
    sim_event_promo: 'Promo / Soldes',
    sim_event_holiday: 'Jours fériés',
    sim_base_risk: 'Risque de base',
    sim_simulated_risk: 'Risque simulé',
    sim_scenario: 'Scénario :',
    sim_stock_sufficient: 'Stock suffisant dans ce scénario',
    sim_stock_days_label: 'Stock estimé pour',
    sim_error_load: 'Impossible de charger les produits',
    sim_error_sim: 'Erreur lors de la simulation',
    sim_days: 'jours',
    sim_velocity: '/j',

    // Compare
    cmp_title: 'Comparaison multi-produits',
    cmp_subtitle: 'Comparez le risque de rupture sur plusieurs produits',
    cmp_selection: 'Sélection',
    cmp_horizon: 'Horizon',
    cmp_compare: 'Comparer',
    cmp_comparing: 'Analyse...',
    cmp_ranking: 'Classement par risque',
    cmp_probability: 'Probabilité de rupture (%)',
    cmp_no_results: 'Aucune comparaison',
    cmp_no_results_hint: 'Sélectionnez 2 à 5 produits et lancez la comparaison',
    cmp_min_2: 'Sélectionnez au moins 2 produits',
    cmp_error: 'Erreur lors de la comparaison',
    cmp_loading: 'Chargement...',
    cmp_radar_risk: 'Risque',
    cmp_radar_delay: 'Délai',
    cmp_radar_min_stock: 'Stock min',

    // ImportCSV
    imp_title: 'Import CSV',
    imp_subtitle: 'Importez vos ventes en masse',
    imp_download_template: 'Télécharger le modèle',
    imp_drop_hint: 'Glissez votre fichier CSV ici',
    imp_browse_hint: 'ou cliquez pour parcourir',
    imp_format_label: 'Format attendu :',
    imp_import_all: 'Importer tout',
    imp_importing: 'Import en cours...',
    imp_col_id: 'ID Produit',
    imp_col_qty: 'Quantité',
    imp_col_status: 'Statut',
    imp_status_pending: 'En attente',
    imp_status_success: 'Importé',
    imp_rows_detected: 'lignes détectées',
    imp_imported: 'importées',
    imp_errors: 'erreurs',

    // Chatbot
    chat_title: 'Conseiller IA',
    chat_subtitle: 'Expert en gestion de stock et supply chain',
    chat_welcome: "Bonjour ! Je suis votre conseiller IA en gestion de stock. Posez-moi vos questions sur vos ruptures, commandes ou stratégies de stock.",
    chat_placeholder: 'Posez votre question...',
    chat_suggest1: 'Comment réduire mon risque de rupture ?',
    chat_suggest2: 'Quelle quantité commander pour 30 jours ?',
    chat_suggest3: 'Quand dois-je passer ma prochaine commande ?',
    chat_suggest4: 'Comment interpréter une probabilité de 70% ?',
    chat_error: 'Erreur de connexion. Réessayez.',

    // Currency & stock value
    curr_title: 'Devise',
    curr_dzd: 'Devise locale',
    curr_eur: 'Euro (€)',
    curr_usd: 'Dollar US ($)',
    curr_saved: 'Devise sauvegardée',
    curr_stock_value: 'Valeur du stock',
    curr_unit_price: 'Prix unitaire',
    curr_set_prices: 'Prix unitaires & valeur du stock',
    curr_set_prices_sub: 'Entrez le prix d\'achat pour calculer la valeur de votre stock',
    curr_total_value: 'Valeur totale estimée',

    // EOQ / Reorder recommendation
    inv_order_rec: 'Commander ~',
    inv_order_unit: 'u.',
    inv_eoq_tip: 'Quantité recommandée basée sur la vélocité et le délai fournisseur',

    // WhatsApp alert
    inv_whatsapp: 'WhatsApp',
    inv_wa_alert: 'Alerter',

    // Algerian holidays in Simulate
    sim_holidays_title: 'Événements détectés dans cette période',
    sim_holidays_tip: 'Anticipez une forte variation de demande !',
    sim_ramadan_tag: 'Ramadan',
    sim_aid_fitr_tag: 'Aïd el-Fitr',
    sim_aid_adha_tag: 'Aïd el-Adha',
    sim_independence_tag: '5 Juillet — Indépendance',
    sim_revolution_tag: '1 Novembre — Révolution',
    sim_labor_tag: '1 Mai — Fête du travail',
    sim_new_year_tag: '1 Janvier — Nouvel An',
    sim_sovereignty_tag: '19 Juin — Souveraineté nationale',

    // Landing page
    land_nav_features: 'Fonctionnalités',
    land_nav_how: 'Comment ça marche',
    land_nav_login: 'Connexion',
    land_nav_start: 'Commencer gratuitement',
    land_badge: 'Intelligence artificielle · Prédiction de ruptures · MENA & FR',
    land_hero_h1a: 'Anticipez',
    land_hero_h1b: 'les ruptures.',
    land_hero_sub: 'Stocky prédit quand votre stock va tomber à zéro — avant que ça arrive.',
    land_hero_sub2: 'Pour les commerçants algériens, français et MENA.',
    land_cta_start: 'Commencer gratuitement',
    land_cta_demo: 'Voir une démo',
    land_free_note: '5 prédictions gratuites · Aucune carte bancaire · Cartes bancaires & CIB acceptés',
    land_stats_accuracy: 'Précision IA',
    land_stats_speed: 'Par prédiction',
    land_stats_sales: 'Ventes en +',
    land_stats_merchants: 'Commerçants',
    land_pain_label: 'Le problème',
    land_pain_h2: 'Chaque commerçant connaît cette douleur',
    land_pain1_title: 'Stock épuisé = client perdu',
    land_pain1_desc: 'Chaque rupture coûte des ventes et votre réputation. Le client qui ne trouve pas va chez le concurrent.',
    land_pain1_loss: '−30% de fidélité',
    land_pain2_title: 'Trop de stock = trésorerie bloquée',
    land_pain2_desc: 'Surstockage paralyse votre cash. Des centaines de milliers immobilisés dans des produits qui ne bougent pas.',
    land_pain2_loss: '−40% cash flow',
    land_pain3_title: 'Décision tardive = perte sèche',
    land_pain3_desc: "Commander après la rupture, c'est déjà trop tard. Les délais fournisseurs font le reste des dégâts.",
    land_pain3_loss: '−15% CA mensuel',
    land_how_label: 'La solution',
    land_how_h2: 'Opérationnel en 5 minutes',
    land_how_sub: 'Trois étapes. Zéro formation. Résultats immédiats.',
    land_step1_title: 'Importez vos ventes',
    land_step1_desc: "CSV glisser-déposer ou saisie manuelle. L'IA apprend votre historique en secondes.",
    land_step2_title: "L'IA prédit les ruptures",
    land_step2_desc: "XGBoost + LSTM calcule la probabilité sur l'horizon choisi (7 → 90 jours).",
    land_step3_title: 'Commandez au bon moment',
    land_step3_desc: 'Alertes email automatiques. Plus jamais trop tôt ni trop tard.',
    land_feat_label: 'Fonctionnalités',
    land_feat_h2a: 'Tout ce dont vous avez besoin.',
    land_feat_h2b: 'Rien de superflu.',
    land_feat1_title: 'IA XGBoost + LSTM',
    land_feat1_desc: 'Double modèle entraîné sur vos données. Intervalle de confiance 95%.',
    land_feat2_title: 'Scan QR instantané',
    land_feat2_desc: 'Scannez un produit, obtenez son score de risque IA en moins de 2 secondes.',
    land_feat3_title: 'Simulation Ramadan',
    land_feat3_desc: 'Anticipez la hausse de demande, les retards fournisseurs, les événements business.',
    land_feat4_title: 'Alertes email auto',
    land_feat4_desc: 'Notification dès que le risque dépasse votre seuil. Zéro surveillance manuelle.',
    land_feat5_title: 'Analytics avancés',
    land_feat5_desc: 'Segmentation ABC, vélocité des ventes, santé du stock en temps réel.',
    land_feat6_title: 'Sécurité enterprise',
    land_feat6_desc: 'JWT, rate limiting, CORS strict, chiffrement bcrypt. Vos données sont protégées.',
    land_market_label: 'Mode marché',
    land_market_h2: 'Conçu pour votre marché',
    land_market_dz_f1: 'Paiement CIB & Edahabia',
    land_market_dz_f2: 'Mode Ramadan (demande ×1.8)',
    land_market_dz_f3: 'Volatilité saisonnière intégrée',
    land_market_dz_f4: 'Anti-rupture prioritaire',
    land_market_dz_f5: 'Interface arabe & français',
    land_market_fr_f1: 'Paiement CB / PayPal',
    land_market_fr_f2: 'Optimisation coût & surstock',
    land_market_fr_f3: 'Conformité RGPD',
    land_market_fr_f4: 'Simulation soldes & fêtes',
    land_market_fr_f5: 'Export PDF & CSV',
    land_testi_label: 'Ils nous font confiance',
    land_testi_h2: 'Des résultats réels',
    land_price_label: 'Tarifs',
    land_price_h2: 'Simple et transparent',
    land_price_sub: '100% algérien (CIB / Edahabia) · ou carte bancaire française',
    land_cta_h2: 'Prêt à ne plus jamais manquer de stock ?',
    land_cta_sub: 'Rejoignez 500+ commerçants qui anticipent déjà leurs ruptures.',
    land_connected: 'connecté',
  },
  ar: {
    // Navigation sidebar
    nav_dashboard: 'لوحة التحكم',
    nav_predict: 'التنبؤ بالذكاء الاصطناعي',
    nav_analytics: 'الإحصائيات',
    nav_inventory: 'صحة المخزون',
    nav_suppliers: 'الموردون',
    nav_chat: 'المستشار الذكي',
    nav_compare: 'مقارنة',
    nav_import: 'استيراد CSV',
    nav_pricing: 'الأسعار',
    nav_profile: 'الملف الشخصي',
    nav_products: 'المنتجات',
    nav_sales: 'المبيعات',
    nav_scan_qr: 'مسح QR',
    nav_simulate: 'محاكاة السيناريوهات',
    nav_reception: 'استقبال المخزون',
    nav_qr_print: 'طباعة QR جماعية',

    // Actions communes
    btn_save: 'حفظ',
    btn_cancel: 'إلغاء',
    btn_delete: 'حذف',
    btn_edit: 'تعديل',
    btn_add: 'إضافة',
    btn_create: 'إنشاء',
    btn_search: 'بحث...',
    btn_export: 'تصدير',
    btn_loading: 'جار التحميل...',
    btn_confirm: 'تأكيد',
    btn_close: 'إغلاق',
    btn_back: 'رجوع',
    btn_next: 'التالي',
    btn_refresh: 'تحديث',

    // Dashboard
    dash_title: 'لوحة التحكم',
    dash_products: 'المنتجات',
    dash_predictions: 'التنبؤات',
    dash_high_risk: 'خطر مرتفع',
    dash_avg_risk: 'متوسط الخطر',
    dash_total_sales: 'إجمالي المبيعات',
    dash_recent_sales: 'مبيعات 30 يوم',
    dash_search_placeholder: 'البحث بالاسم أو الرمز (SKU)...',
    dash_no_products: 'لا توجد منتجات',
    dash_no_products_sub: 'ابدأ بإنشاء منتج لتتبع مخزونك',
    dash_predict_all: 'تنبؤ شامل',
    dash_new_product: 'منتج جديد',
    dash_onboarding_title: 'مرحباً بك في StockSense!',
    dash_onboarding_subtitle: 'اتبع هذه الخطوات الـ3 للبدء',
    dash_create_product_btn: 'إنشاء منتج',

    // Predict
    pred_title: 'التنبؤ بالذكاء الاصطناعي',
    pred_select_product: 'اختر منتجاً',
    pred_horizon: 'أفق التنبؤ',
    pred_days: 'يوم',
    pred_run: 'تشغيل التنبؤ',
    pred_probability: 'احتمالية نفاد المخزون',
    pred_result_high: 'خطر مرتفع',
    pred_result_medium: 'خطر متوسط',
    pred_result_low: 'خطر منخفض',
    pred_trials_left: 'تجارب مجانية متبقية',

    // Inventory Health
    inv_title: 'صحة المخزون',
    inv_product: 'المنتج',
    inv_stock: 'المخزون',
    inv_daily_sales: 'سرعة 30 يوم',
    inv_reorder: 'نقطة إعادة الطلب',
    inv_coverage: 'التغطية',
    inv_status: 'الحالة',
    inv_actions: 'الإجراءات',
    inv_history: 'السجل',
    inv_edit: 'تعديل',
    inv_critical: 'حرج',
    inv_warning: 'إعادة طلب',
    inv_ok: 'جيد',
    inv_overstock: 'مخزون زائد',
    inv_trend: 'الاتجاه',
    inv_no_products: 'لا توجد منتجات',
    inv_no_products_sub: 'أنشئ منتجات وسجّل مبيعات لعرض البيانات',

    // Suppliers
    sup_title: 'الموردون',
    sup_add: 'إضافة مورد',
    sup_name: 'اسم المورد',
    sup_email: 'البريد الإلكتروني',
    sup_phone: 'الهاتف',
    sup_lead_time: 'مدة التسليم (أيام)',
    sup_no_suppliers: 'لا يوجد موردون مسجلون',
    sup_no_suppliers_sub: 'أضف موردين لربطهم بمنتجاتك',
    sup_new: 'مورد جديد',
    sup_edit: 'تعديل المورد',
    sup_create_btn: 'إنشاء المورد',
    sup_save_btn: 'حفظ',

    // Profile
    prof_title: 'ملفي الشخصي',
    prof_change_pwd: 'تغيير كلمة المرور',
    prof_current_pwd: 'كلمة المرور الحالية',
    prof_new_pwd: 'كلمة المرور الجديدة',
    prof_confirm_pwd: 'تأكيد',
    prof_alert_pref: 'تفضيلات التنبيهات',
    prof_alert_threshold: 'حد تنبيه البريد',
    prof_pro_active: 'الخطة الاحترافية نشطة',
    prof_upgrade: 'الترقية إلى Pro',
    prof_logout: 'تسجيل الخروج',
    prof_update_pwd: 'تحديث',
    prof_danger_zone: 'المنطقة الخطرة',
    prof_danger_sub: 'تسجيل الخروج من جميع الأجهزة.',

    // Predict page extras
    pred_params: 'المعاملات',
    pred_back: 'العودة إلى لوحة التحكم',
    pred_gauge: 'مقياس الخطر',
    pred_chart: 'تطور الخطر',
    pred_days_rupture: 'أيام حتى النفاد المتوقع',
    pred_rupture_date: 'تاريخ النفاد المتوقع',
    pred_confidence: 'فترة الثقة',
    pred_analysis: 'تحليل...',

    // Inventory Health extras
    inv_refresh: 'تحديث',
    inv_filter_all: 'الكل',
    inv_filter_critical: 'حرج',
    inv_filter_warning: 'إعادة طلب',
    inv_filter_ok: 'جيد',
    inv_filter_overstock: 'مخزون زائد',
    inv_abc: 'تصنيف ABC',
    inv_score_velocity: 'سرعة المبيعات',
    inv_history_title: 'سجل المخزون',
    inv_no_movements: 'لا توجد حركات مسجلة',
    inv_add_stock: 'إضافة مخزون',
    inv_delete: 'حذف',

    // Suppliers extras
    sup_refresh: 'تحديث',
    sup_contact_email: 'بريد الاتصال',
    sup_phone_label: 'الهاتف',
    sup_lead_label: 'مدة التسليم',
    sup_optional: '(اختياري)',
    sup_loading: 'جار التحميل...',

    // Dashboard titles
    dash_overview: 'نظرة عامة في الوقت الفعلي',
    dash_alerts: 'تنبيهات المخزون',
    dash_batch_title: 'تحليل سريع — جميع المنتجات',
    dash_batch_sub: 'توقعات النفاد لـ 30 يوماً',
    dash_catalog: 'كتالوج المنتجات',

    // Predict subtitle
    pred_subtitle: 'حلّل خطر نفاد المخزون',

    // QR Scanner
    scan_title: 'مسح المنتج',
    scan_subtitle: 'QR Code · EAN-13 · Code 128 · UPC · والمزيد',
    scan_point: 'وجّه نحو QR code أو الباركود',
    scan_camera_start: 'تشغيل الكاميرا',
    scan_manual_label: 'SKU أو معرف المنتج أو رقم الباركود',
    scan_analyze: 'تحليل',
    scan_new_scan: 'مسح منتج آخر',
    scan_new_search: 'بحث جديد',
    scan_no_code: 'أدخل SKU أو معرفاً أو رقم باركود',
    scan_loading: 'التحليل الذكي جارٍ...',
    scan_camera_mode: 'الكاميرا',
    scan_manual_mode: 'يدوي',

    // Common
    status_subscribed: 'Pro نشط',
    status_free: 'الخطة المجانية',
    confirm_delete_title: 'تأكيد الحذف',
    confirm_delete_msg: 'هذا الإجراء لا يمكن التراجع عنه.',
    toast_saved: 'تم الحفظ بنجاح',
    toast_deleted: 'تم الحذف بنجاح',
    toast_error: 'حدث خطأ',
    theme_light: 'الوضع الفاتح',
    theme_dark: 'الوضع الداكن',
    logout: 'تسجيل الخروج',

    // Risk labels shared
    risk_low: 'منخفض',
    risk_medium: 'متوسط',
    risk_high: 'مرتفع',
    risk_critical: 'حرج',

    // QR Scanner result + errors
    scan_risk_label: 'خطر النفاد (30 يوم)',
    scan_stock_label: 'المخزون',
    scan_safety_label: 'أمان',
    scan_delay_label: 'مدة',
    scan_detected: 'تم اكتشافه',
    scan_err_denied: 'تم رفض إذن الكاميرا. أتح الوصول في إعدادات المتصفح.',
    scan_err_no_cam: 'لا توجد كاميرا على هذا الجهاز.',
    scan_err_generic: 'تعذّر الوصول إلى الكاميرا. جرّب الوضع اليدوي.',
    scan_not_found: 'لا يوجد منتج لهذا الرمز',

    // Dashboard panel content
    dash_qa_predict: 'إطلاق تنبؤ',
    dash_qa_predict_sub: 'توقع نفاد المخزون',
    dash_qa_sale: 'تسجيل بيع',
    dash_qa_sale_sub: 'تحديث المخزون',
    dash_qa_analytics: 'عرض التحليلات',
    dash_qa_analytics_sub: 'السجل والرسوم البيانية',
    dash_see_all: 'عرض الكل',
    dash_top_risks: 'أعلى المخاطر',
    dash_badge_high: 'مرتفع',
    dash_badge_medium: 'متوسط',
    dash_batch_empty: 'اضغط "تنبؤ شامل" لتحليل',
    dash_step1_title: 'إنشاء أول منتج',
    dash_step1_desc: 'أضف منتجاً إلى كتالوجك مع رمز SKU ومدة التوريد.',
    dash_step1_cta: 'إنشاء منتج',
    dash_step2_title: 'إدخال المخزون الأولي',
    dash_step2_desc: 'سجّل أولى مبيعاتك أو استورد سجل المبيعات CSV.',
    dash_step2_cta: 'تسجيل بيع',
    dash_step3_title: 'إطلاق أول تنبؤ ذكي',
    dash_step3_desc: 'احصل على احتمالية نفاد المخزون والتاريخ المتوقع لكل منتج.',
    dash_step3_cta: 'تنبؤ الآن',
    dash_step_label: 'خطوة',
    dash_alert_stock: 'المخزون:',
    dash_alert_reorder: 'إعادة طلب:',
    dash_alert_critical: 'حرج',
    dash_alert_warning: 'إعادة طلب',
    dash_prod_col: 'المنتج',
    dash_delay_col: 'المدة',
    dash_safety_col: 'حد الأمان',

    // Predict result panel
    pred_stable: 'مستقر',
    pred_no_risk: 'لا خطر فوري',
    pred_no_result: 'لا توجد توقعات',
    pred_hint: 'حدد منتجاً وابدأ التحليل',
    pred_rupture_label: 'نفاد متوقع',
    pred_confidence_label: 'فترة الثقة',
    pred_ic_label: 'فا 95%',
    pred_evolution: 'التطور على',
    pred_critical_zone: 'المنطقة الحرجة نحو',

    // CreateProduct
    cp_title: 'منتج جديد',
    cp_subtitle: 'أضف منتجاً إلى كتالوجك',
    cp_back: 'العودة إلى لوحة التحكم',
    cp_name: 'اسم المنتج',
    cp_sku: 'SKU',
    cp_sku_note: 'رمز فريد',
    cp_sku_hint: 'الرمز الفريد للمنتج (مثال: PROD-001). لا يمكن تعديله بعد الإنشاء.',
    cp_lead_time: 'مدة التسليم',
    cp_lead_unit: 'أيام',
    cp_lead_hint: 'متوسط المدة بالأيام بين طلب المورد والاستلام في المخزن',
    cp_safety: 'مخزون الأمان',
    cp_safety_unit: 'وحدات',
    cp_safety_hint: 'الكمية الدنيا التي يجب الاحتفاظ بها دائماً للطوارئ',
    cp_initial_stock: 'المخزون الأولي',
    cp_initial_hint: 'الكمية المتوفرة حالياً',
    cp_supplier: 'المورد',
    cp_no_supplier: '— بلا مورد —',
    cp_supplier_no_data: 'لا يوجد موردون.',
    cp_supplier_create: 'إنشاء مورد',
    cp_submit: 'إنشاء المنتج',
    cp_success: 'تم إنشاء المنتج بنجاح!',
    cp_error: 'خطأ أثناء الإنشاء',
    cp_scan_sku: 'مسح',

    // InventoryHealth panel
    inv_velocity_title: 'سرعة المبيعات لكل منتج',
    inv_velocity_sub: 'متوسط المبيعات اليومية على 3 نوافذ زمنية',
    inv_units: 'وحدات',
    inv_stable: 'مستقر',
    inv_tile_critical: 'حرج (مخزون 0)',
    inv_tile_warning: 'إعادة طلب عاجلة',
    inv_tile_ok: 'مخزون جيد',
    inv_tile_overstock: 'مخزون زائد',

    // AddSale
    sale_title: 'تسجيل بيع',
    sale_subtitle: 'تخفيض المخزون',
    sale_back: 'العودة إلى لوحة التحكم',
    sale_product: 'المنتج',
    sale_product_hint: 'حدد المنتج الذي تسجل له البيع',
    sale_qty: 'الكمية المباعة',
    sale_qty_hint: 'عدد الوحدات المباعة — سيتم تحديث المخزون تلقائياً',
    sale_delay: 'المدة:',
    sale_min_stock: 'حد المخزون:',
    sale_submit: 'تسجيل البيع',
    sale_success: 'تم تسجيل البيع!',
    sale_error: 'خطأ أثناء التسجيل',
    sale_no_products: 'لا توجد منتجات متاحة.',
    sale_create_product: 'إنشاء منتج',
    sale_loading: 'جار تحميل المنتجات...',

    // Analytics
    ana_title: 'الإحصائيات',
    ana_subtitle: 'عرض تفصيلي لبياناتك',
    ana_export_pdf: 'تصدير PDF',
    ana_export_pred: 'توقعات CSV',
    ana_export_sales: 'مبيعات CSV',
    ana_products: 'المنتجات',
    ana_predictions: 'مجموع التوقعات',
    ana_avg_prob: 'متوسط الاحتمالية',
    ana_high_risk_sub: 'بخطر مرتفع',
    ana_recent_sales_sub: 'مبيعات هذا الشهر',
    ana_sales_by_product: 'المبيعات لكل منتج',
    ana_no_sales: 'لا توجد مبيعات مسجلة',
    ana_risk_dist: 'توزيع المخاطر',
    ana_no_preds: 'لا توجد توقعات',
    ana_history_title: 'سجل التوقعات',
    ana_new_prediction: 'توقع جديد →',
    ana_no_history: 'لم تُجرَ أي توقعات',
    ana_error: 'خطأ في تحميل الإحصائيات',
    ana_export_ok: 'تم تنزيل التصدير!',
    ana_export_error: 'خطأ أثناء التصدير',
    ana_date: 'التاريخ',
    ana_horizon: 'الأفق',
    ana_probability: 'الاحتمالية',
    ana_risk: 'الخطر',
    ana_sales_count: 'مبيعات',
    ana_preds_count: 'توقعات',
    ana_total: 'الإجمالي',
    ana_tooltip_pdf: 'طباعة أو حفظ الإحصائيات كـ PDF',
    ana_tooltip_csv: 'تنزيل بياناتك في Excel أو Google Sheets',

    // Simulate
    sim_title: 'محاكاة السيناريوهات',
    sim_subtitle: 'توقع التأثير قبل حدوثه',
    sim_no_products: 'لا توجد منتجات',
    sim_no_products_msg: 'أنشئ منتجاً أولاً في المنتجات لإطلاق المحاكاة.',
    sim_product_label: 'المنتج للمحاكاة',
    sim_product_none: '— لا يوجد منتج —',
    sim_horizon_label: 'أفق التنبؤ',
    sim_demand_label: 'تغير الطلب',
    sim_supplier_label: 'تأخر المورد',
    sim_event_label: 'حدث خارجي',
    sim_submit: 'إطلاق المحاكاة',
    sim_submitting: 'المحاكاة جارية...',
    sim_event_none: 'لا حدث',
    sim_event_ramadan: 'رمضان',
    sim_event_weather: 'طقس متطرف',
    sim_event_promo: 'عرض / تخفيضات',
    sim_event_holiday: 'أعياد رسمية',
    sim_base_risk: 'الخطر الأساسي',
    sim_simulated_risk: 'الخطر المحاكى',
    sim_scenario: 'السيناريو:',
    sim_stock_sufficient: 'المخزون كافٍ في هذا السيناريو',
    sim_stock_days_label: 'مخزون مُقدَّر لـ',
    sim_error_load: 'تعذّر تحميل المنتجات',
    sim_error_sim: 'خطأ أثناء المحاكاة',
    sim_days: 'أيام',
    sim_velocity: '/ي',

    // Compare
    cmp_title: 'مقارنة متعددة المنتجات',
    cmp_subtitle: 'قارن خطر النفاد عبر منتجات متعددة',
    cmp_selection: 'الاختيار',
    cmp_horizon: 'الأفق',
    cmp_compare: 'مقارنة',
    cmp_comparing: 'تحليل...',
    cmp_ranking: 'الترتيب حسب الخطر',
    cmp_probability: 'احتمالية النفاد (%)',
    cmp_no_results: 'لا توجد مقارنة',
    cmp_no_results_hint: 'حدد 2 إلى 5 منتجات وابدأ المقارنة',
    cmp_min_2: 'حدد منتجين على الأقل',
    cmp_error: 'خطأ أثناء المقارنة',
    cmp_loading: 'جار التحميل...',
    cmp_radar_risk: 'الخطر',
    cmp_radar_delay: 'المدة',
    cmp_radar_min_stock: 'الحد الأدنى',

    // ImportCSV
    imp_title: 'استيراد CSV',
    imp_subtitle: 'استورد مبيعاتك بالجملة',
    imp_download_template: 'تنزيل النموذج',
    imp_drop_hint: 'اسحب ملف CSV هنا',
    imp_browse_hint: 'أو انقر للتصفح',
    imp_format_label: 'الصيغة المتوقعة:',
    imp_import_all: 'استيراد الكل',
    imp_importing: 'جار الاستيراد...',
    imp_col_id: 'معرف المنتج',
    imp_col_qty: 'الكمية',
    imp_col_status: 'الحالة',
    imp_status_pending: 'في الانتظار',
    imp_status_success: 'تم الاستيراد',
    imp_rows_detected: 'سطور مكتشفة',
    imp_imported: 'مستوردة',
    imp_errors: 'أخطاء',

    // Chatbot
    chat_title: 'المستشار الذكي',
    chat_subtitle: 'خبير في إدارة المخزون وسلسلة التوريد',
    chat_welcome: 'مرحباً! أنا مستشارك الذكي لإدارة المخزون. اسألني عن نفاد المخزون أو الطلبات أو استراتيجيات المخزون.',
    chat_placeholder: 'اطرح سؤالك...',
    chat_suggest1: 'كيف أقلل خطر نفاد المخزون؟',
    chat_suggest2: 'ما الكمية التي أطلبها لـ 30 يوماً؟',
    chat_suggest3: 'متى يجب أن أضع طلبيتي القادمة؟',
    chat_suggest4: 'كيف أفسر احتمالية 70%؟',
    chat_error: 'خطأ في الاتصال. حاول مجدداً.',

    // Currency & stock value
    curr_title: 'العملة',
    curr_dzd: 'العملة المحلية',
    curr_eur: 'يورو (€)',
    curr_usd: 'دولار أمريكي ($)',
    curr_saved: 'تم حفظ العملة',
    curr_stock_value: 'قيمة المخزون',
    curr_unit_price: 'سعر الوحدة',
    curr_set_prices: 'أسعار الوحدات وقيمة المخزون',
    curr_set_prices_sub: 'أدخل سعر الشراء لحساب قيمة مخزونك',
    curr_total_value: 'القيمة الإجمالية المقدرة',

    // EOQ / Reorder recommendation
    inv_order_rec: 'اطلب ~',
    inv_order_unit: 'و.',
    inv_eoq_tip: 'الكمية الموصى بها بناءً على السرعة ومدة التوريد',

    // WhatsApp alert
    inv_whatsapp: 'واتساب',
    inv_wa_alert: 'تنبيه',

    // Algerian holidays in Simulate
    sim_holidays_title: 'أحداث مكتشفة في هذه الفترة',
    sim_holidays_tip: 'توقع تغيراً كبيراً في الطلب!',
    sim_ramadan_tag: 'رمضان',
    sim_aid_fitr_tag: 'عيد الفطر',
    sim_aid_adha_tag: 'عيد الأضحى',
    sim_independence_tag: '5 يوليو — الاستقلال',
    sim_revolution_tag: '1 نوفمبر — الثورة',
    sim_labor_tag: '1 مايو — عيد العمال',
    sim_new_year_tag: '1 يناير — رأس السنة',
    sim_sovereignty_tag: '19 يونيو — السيادة الوطنية',

    // Landing page
    land_nav_features: 'المميزات',
    land_nav_how: 'كيف يعمل',
    land_nav_login: 'تسجيل الدخول',
    land_nav_start: 'ابدأ مجاناً',
    land_badge: 'ذكاء اصطناعي · توقع نفاد المخزون · MENA & FR',
    land_hero_h1a: 'توقّع',
    land_hero_h1b: 'نفاد المخزون.',
    land_hero_sub: 'Stocky يتنبأ بنفاد مخزونك قبل أن يحدث.',
    land_hero_sub2: 'للتجار الجزائريين والعرب والفرنسيين.',
    land_cta_start: 'ابدأ مجاناً',
    land_cta_demo: 'مشاهدة العرض',
    land_free_note: '5 تنبؤات مجانية · بدون بطاقة بنكية · CIB و Edahabia مقبولة',
    land_stats_accuracy: 'دقة الذكاء الاصطناعي',
    land_stats_speed: 'لكل تنبؤ',
    land_stats_sales: 'زيادة في المبيعات',
    land_stats_merchants: 'تاجر',
    land_pain_label: 'المشكلة',
    land_pain_h2: 'كل تاجر يعرف هذا الألم',
    land_pain1_title: 'نفاد المخزون = خسارة العميل',
    land_pain1_desc: 'كل نفاد مخزون يكلفك مبيعات وسمعة. العميل الذي لا يجد ما يريد يذهب للمنافس.',
    land_pain1_loss: '−30% من الولاء',
    land_pain2_title: 'مخزون زائد = أموال مجمّدة',
    land_pain2_desc: 'الإفراط في التخزين يشلّ سيولتك. آلاف الدنانير محتجزة في منتجات لا تتحرك.',
    land_pain2_loss: '−40% تدفق نقدي',
    land_pain3_title: 'قرار متأخر = خسارة صافية',
    land_pain3_desc: 'الطلب بعد النفاد فات الأوان. مهل التوريد تكمل الضرر.',
    land_pain3_loss: '−15% رقم أعمال شهري',
    land_how_label: 'الحل',
    land_how_h2: 'جاهز في 5 دقائق',
    land_how_sub: 'ثلاث خطوات. صفر تدريب. نتائج فورية.',
    land_step1_title: 'استورد مبيعاتك',
    land_step1_desc: 'CSV بالسحب والإفلات أو إدخال يدوي. الذكاء الاصطناعي يتعلم تاريخك في ثوانٍ.',
    land_step2_title: 'الذكاء الاصطناعي يتنبأ بالنفاد',
    land_step2_desc: 'XGBoost + LSTM يحسب الاحتمالية على الأفق المختار (7 → 90 يوماً).',
    land_step3_title: 'اطلب في الوقت المناسب',
    land_step3_desc: 'تنبيهات بريد إلكتروني تلقائية. لن تكون متأخراً أبداً.',
    land_feat_label: 'المميزات',
    land_feat_h2a: 'كل ما تحتاجه.',
    land_feat_h2b: 'لا شيء زائد.',
    land_feat1_title: 'ذكاء اصطناعي XGBoost + LSTM',
    land_feat1_desc: 'نموذج مزدوج مدرَّب على بياناتك. فترة ثقة 95%.',
    land_feat2_title: 'مسح QR فوري',
    land_feat2_desc: 'امسح منتجاً، احصل على درجة الخطر في أقل من ثانيتين.',
    land_feat3_title: 'محاكاة رمضان',
    land_feat3_desc: 'توقع ارتفاع الطلب، تأخيرات الموردين، الأحداث التجارية.',
    land_feat4_title: 'تنبيهات بريد تلقائية',
    land_feat4_desc: 'إشعار فور تجاوز الخطر لعتبتك. صفر مراقبة يدوية.',
    land_feat5_title: 'تحليلات متقدمة',
    land_feat5_desc: 'تصنيف ABC، سرعة المبيعات، صحة المخزون في الوقت الحقيقي.',
    land_feat6_title: 'أمان للمؤسسات',
    land_feat6_desc: 'JWT، تحديد المعدل، CORS صارم، تشفير bcrypt. بياناتك محمية.',
    land_market_label: 'وضع السوق',
    land_market_h2: 'مصمم لسوقك',
    land_market_dz_f1: 'دفع CIB و Edahabia',
    land_market_dz_f2: 'وضع رمضان (طلب ×1.8)',
    land_market_dz_f3: 'تقلبات موسمية مدمجة',
    land_market_dz_f4: 'أولوية منع النفاد',
    land_market_dz_f5: 'واجهة عربية وفرنسية',
    land_market_fr_f1: 'دفع CB / PayPal',
    land_market_fr_f2: 'تحسين التكلفة والمخزون الزائد',
    land_market_fr_f3: 'توافق مع RGPD',
    land_market_fr_f4: 'محاكاة التخفيضات والأعياد',
    land_market_fr_f5: 'تصدير PDF و CSV',
    land_testi_label: 'يثقون بنا',
    land_testi_h2: 'نتائج حقيقية',
    land_price_label: 'الأسعار',
    land_price_h2: 'بسيط وشفاف',
    land_price_sub: '100% جزائري (CIB / Edahabia) · أو بطاقة بنكية فرنسية',
    land_cta_h2: 'هل أنت مستعد لعدم نفاد مخزونك أبداً؟',
    land_cta_sub: 'انضم إلى أكثر من 500 تاجر يتوقعون نفاد مخزونهم مسبقاً.',
    land_connected: 'متصل',
  },
}

type TranslationKey = keyof typeof translations.fr

interface LanguageContextType {
  lang: Lang
  setLang: (lang: Lang) => void
  t: (key: TranslationKey) => string
  isRTL: boolean
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'fr',
  setLang: () => {},
  t: (key) => key,
  isRTL: false,
})

function applyLangToDOM(l: Lang) {
  const isAr = l === 'ar'
  document.documentElement.dir = isAr ? 'rtl' : 'ltr'
  document.documentElement.lang = l
  if (isAr) {
    document.documentElement.classList.add('lang-ar')
  } else {
    document.documentElement.classList.remove('lang-ar')
  }
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => (localStorage.getItem('lang') as Lang) || 'fr')

  // Apply on mount
  useEffect(() => { applyLangToDOM(lang) }, [])

  function setLang(l: Lang) {
    setLangState(l)
    localStorage.setItem('lang', l)
    applyLangToDOM(l)
  }

  const t = (key: TranslationKey): string =>
    (translations[lang] as Record<string, string>)[key] || (translations.fr as Record<string, string>)[key] || key

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isRTL: lang === 'ar' }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
